<a href="https://colab.research.google.com/github/Dhruvi-1234/Numpy_task/blob/main/Copy_of_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
np.show_config()

1.21.6
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSS

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x = np.array([10,20,30,40])
print("Memory size of numpy array in bytes:",x.size * x.itemsize)

Memory size of numpy array in bytes: 32


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out



#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
y = np.zeros(10)
y[4]=1
print(y)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
z = np.arange(1,50)
print(z)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
a = np.array([10,2,30,44,58])
a[::-1]

array([58, 44, 30,  2, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]




#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
y = np.array([1,2,0,0,4,0])
print(np.nonzero(y))

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
A = np.random.random((3,3,3))
print(A)

[[[0.51950908 0.3047339  0.01870668]
  [0.46053575 0.33295714 0.40921073]
  [0.23373576 0.49833573 0.88449328]]

 [[0.90072537 0.4453152  0.65085501]
  [0.8843197  0.59318155 0.23072638]
  [0.53507026 0.00628649 0.42985305]]

 [[0.86504936 0.91372563 0.31472345]
  [0.30738243 0.05716595 0.94700094]
  [0.02484436 0.72050561 0.59250948]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
X = np.random.random((10,10))
Xmin = X.min()
Xmax = X.max()
print(Xmin,Xmax)

0.006328330849329156 0.9856569484052345


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
Y = np.random.random(30)
print(Y.mean())

0.5229980177489812


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
Y = np.ones((10,10))
Y = np.pad(Y,pad_width = 1,mode = 'constant',constant_values = 0)
print(Y)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
Z = np.diag(1+np.arange(4),k = -1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
B = np.unravel_index(100,(6,7,8))
print(B)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
X = np.tile(([0,1],[1,0]),(4,4))
print(X)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
Y = np.random.random((5,5))
Ymin = Y.min()
Ymax = Y.max()
N = (Y - Ymin)/(Ymax -Ymin)
print(N)

[[0.34473549 0.95544625 0.13239755 1.         0.75137534]
 [0.50814059 0.44145789 0.88678846 0.69695935 0.33596703]
 [0.47833814 0.63137956 0.15266164 0.0714906  0.87990052]
 [0.21777498 0.         0.49985694 0.55090148 0.63384366]
 [0.50940351 0.91709974 0.39009542 0.30280006 0.91558973]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),("g", np.ubyte, 1),("b", np.ubyte, 1),("a", np.ubyte, 1)])
color

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x = np.random.random((5,3))
y = np.random.random((3,2))
print(np.dot(x,y))

[[0.52704645 0.66694143]
 [0.41129582 0.57078896]
 [0.28075198 0.34472147]
 [0.48924996 0.55949658]
 [0.9176873  1.07616053]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
Z = np.arange(11)
Z[(Z>3)&(Z<=8)]*=-1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = np.arange(3)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
#print(Z<Z>Z) = error


[1 1 4]
[0 1 2]
[False False False]
[0.+0.j 0.+1.j 0.+2.j]
[0. 1. 2.]


#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


nan
0
[-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
#def round_array(x,y):
  #return np.round(x,y)
#test = np.array([32.115, 51.5, 0.112])
#print(round_array(test,0))
Z = np.random.uniform(-10,+10,10)
print(Z)
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-3.77359228  2.67620651  8.18849347 -6.16153413  2.38835014  5.66681445
 -5.30705386 -4.48062169  2.79062879 -7.60291054]
[-4.  3.  9. -7.  3.  6. -6. -5.  3. -8.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
X1 = np.random.randint(0,10,10)
X2 = np.random.randint(0,10,10)
Z = np.intersect1d(X1,X2)
print(Z)

[0 2 5 9]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
data = np.random.random(1000).reshape(10, 10,10) * np.nan
np.seterr(all="ignore")
np.nanmedian(data, axis=[1, 2])

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan])

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
print(np.sqrt(-1) == np.emath.sqrt(-1))

False


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday =  print(np.datetime64('today','D') - np.timedelta64(1,'D'))
today = print(np.datetime64('today','D'))
tomorrow = print(np.datetime64('today','D') + np.timedelta64(1,'D'))

2022-11-04
2022-11-05
2022-11-06


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
Z = np.arange('2016-07','2016-08',dtype = 'datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out = B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
Z = np.random.randint(0,10,10)
print(Z-Z%1)
print(np.floor(Z))
print(np.ceil(z)-1)
print(Z.astype(int))
print()

[4 7 5 7 0 1 6 0 6 1]
[4. 7. 5. 7. 0. 1. 6. 0. 6. 1.]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35.
 36. 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48.]
[4 7 5 7 0 1 6 0 6 1]



#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x = np.zeros((5,5))
x+=np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
arr = np.fromiter(generate(), dtype=float, count=-1)
print(arr)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
arr = np.linspace(0,1,11,endpoint=False)[1:]
arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
arr = np.random.random(10)
arr.sort()
arr

array([0.00182674, 0.08877367, 0.27652588, 0.3804509 , 0.44427808,
       0.58823243, 0.64345659, 0.64543739, 0.72298464, 0.80117329])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
arr = np.arange(6)
np.add.reduce(arr)

15

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(0,8,10)
B = np.random.randint(0,8,10)
equal = np.array_equal(A,B)
print(equal)

False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
arr = np.ones(6)
arr.flags.writeable = False
arr[0] = 0

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
y = np.random.random((10,2))
a = y[:,0]
b = y[:,1]
R = np.sqrt(a**2+b**2)
T = np.arctan2(b,a)
print(R)
print(T)

[0.75700195 0.94436518 0.84770764 1.35746029 0.39545383 0.69458793
 0.54950435 0.9395515  0.83450158 0.57690125]
[0.03898371 0.68242913 1.41740672 0.82649895 0.53455896 1.33843933
 0.96963555 1.22483945 0.67277712 1.26989614]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
arr = np.random.random(10)
arr[arr.argmax()] = 0
print(arr)

[0.86144739 0.22457023 0.         0.02071024 0.78906461 0.29482547
 0.22578908 0.96870199 0.21515807 0.69279046]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
arr = np.zeros((5,5), [('x',float),('y',float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(arr)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=float("inf"))
arr = np.zeros((4,6))
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
arr = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(arr-v)).argmin()
print(arr[index])

60


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
arr = np.zeros(6,[('postion',[('x',float,1),('y',float,1)]),('color',[('r', float, 1),('g', float, 1),('b', float, 1)])])
print(arr)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """Entry point for launching an IPython kernel.


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
arr = np.random.random((10,2))
X,Y = np.atleast_2d(arr[:,0], arr[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.54297666 0.31088246 0.43769219 0.28910128 0.19385736
  0.79642246 0.52337207 0.68885927 0.6258706 ]
 [0.54297666 0.         0.77425221 0.10652206 0.56354131 0.70145593
  0.25477694 0.53069706 0.47558302 0.09313407]
 [0.31088246 0.77425221 0.         0.66983282 0.25055677 0.12658733
  1.01012598 0.50062612 0.72856356 0.86590052]
 [0.43769219 0.10652206 0.66983282 0.         0.46680419 0.59505699
  0.35874981 0.47016786 0.46338469 0.1961877 ]
 [0.28910128 0.56354131 0.25055677 0.46680419 0.         0.25678719
  0.78157364 0.26769957 0.4831125  0.65666471]
 [0.19385736 0.70145593 0.12658733 0.59505699 0.25678719 0.
  0.94756286 0.52446134 0.73446754 0.79014382]
 [0.79642246 0.25477694 1.01012598 0.35874981 0.78157364 0.94756286
  0.         0.67747409 0.53187935 0.18809275]
 [0.52337207 0.53069706 0.50062612 0.47016786 0.26769957 0.52446134
  0.67747409 0.         0.23682187 0.61378112]
 [0.68885927 0.47558302 0.72856356 0.46338469 0.4831125  0.73446754
  0.53187935 0.23682

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
arr = (np.random.rand(10)*100).astype(np.float32)
Y = arr.view(np.int32)
Y[:] = arr
print(Y)

[77 73 50 79 34 31 41 51 80 59]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11''')
arr = np.genfromtxt(s,delimiter = ",",dtype =np.int)
print(arr)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  """


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
arr = np.arange(6).reshape(3,2)
for index,value in np.ndenumerate(arr):
  print(index,value)
for index in np.ndindex(arr.shape):
  print(index,arr[index])

(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5
(0, 0) 0
(0, 1) 1
(1, 0) 2
(1, 1) 3
(2, 0) 4
(2, 1) 5


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x,y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
d = np.sqrt(x*x+y*y)
sigma, mu = 1.0, 0.0
g = np.exp(-( (d-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(g)


[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 6
p = 2
arr = np.zeros((n,n))
np.put(arr, np.random.choice(range(n*n), p, replace=False),1)
print(arr)

[[0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
arr = np.random.rand(5,10)
Y = arr-arr.mean(axis = 1,keepdims = True)
print(Y)

[[-0.34710388 -0.2117309  -0.14564077  0.26844608 -0.06612881  0.06653626
   0.33223234 -0.04907596  0.27128774 -0.1188221 ]
 [-0.24570032  0.40251921 -0.34221086  0.44283993  0.03392975 -0.27641713
   0.40805752 -0.418578    0.28915008 -0.29359019]
 [-0.28878731 -0.12101799 -0.0773646   0.42484636 -0.11927802 -0.16038878
   0.1089908  -0.01735041 -0.28149944  0.53184937]
 [ 0.31690325  0.48262047 -0.17107916  0.03594602  0.05060188  0.39086796
   0.04271534 -0.46720878 -0.20888456 -0.4724824 ]
 [ 0.38634319 -0.41168481 -0.34987276  0.47806975  0.43323698 -0.45973773
  -0.22671219 -0.2877952   0.00164005  0.4365127 ]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
a = np.array([[9, 2, 3],[4, 5, 6],[7, 0, 5]])
a = a[a[:,1].argsort()]
print(a)

[[7 0 5]
 [9 2 3]
 [4 5 6]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
num=np.random.randint(0,3,(3,10))
print((~arr.any(axis=0)).any())

False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
arr = np.random.uniform(0,1,10)
a = 0.5
m = arr.flat[np.abs(arr - a).argmin()]
print(m)

0.5913671635455922


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(1,3)
B = np.arange(3).reshape(3,1)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
arr = np.ones(10)
I = np.random.randint(0,len(arr),20)
arr += np.bincount(I, minlength=len(arr))
print(arr)

[3. 2. 3. 5. 4. 3. 4. 2. 3. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
arr = np.random.randint(0,10,(3,4,3,4))
sum = arr.sum(axis=(-2,-1))
print(sum)

[[52 52 48 58]
 [50 39 35 48]
 [41 55 52 50]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)


[0.41502625 0.53505454 0.52426901 0.41588417 0.57594774 0.71737094
 0.48346834 0.64907497 0.43935503 0.47599171]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
arr1 = np.random.uniform(0,1,(5,5))
arr2 = np.random.uniform(0,1,(5,5))
np.diag(np.dot(arr1, arr2))

array([1.7486913 , 1.49540387, 2.09948136, 1.94015225, 1.3478665 ])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
arr = np.array([1,2,3,4,5])
nz = 3
arr0 = np.zeros(len(arr) + (len(arr)-1)*(nz))
arr0[::nz+1] = arr
print(arr0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
arr1 = np.ones((5,5,3))
arr2 = np.ones((5,5))
print(arr1 * arr2[:,:,None])

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
x = np.arange(24).reshape(6,4)
x[[1,0]]=x[[0,1]]
print(x)

[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 2, 13) ( 2, 32) ( 8, 84) ( 8, 89) (12, 66) (12, 73) (13, 32) (22, 80)
 (22, 93) (29, 75) (29, 94) (38, 56) (38, 82) (41, 43) (41, 44) (41, 67)
 (41, 82) (43, 67) (44, 82) (48, 68) (48, 76) (50, 59) (50, 84) (56, 82)
 (59, 84) (66, 73) (68, 76) (75, 94) (80, 93) (84, 89)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C =  np.bincount([1,4,6,2,3,1,1])
A = np.repeat(np.arange(len(C)),C)
print(A)

[1 1 1 2 3 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a,n =3):
  test = np.cumsum(a,dtype = float)
  test[n:]=test[n:]-test[:-n]
  return test[n - 1:] / n
arr = np.arange(20)
print(moving_average(arr,n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return np.lib.stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
x = np.random.randint(0,2,50)
print ('original: ')
print (x)
print('Negating a boolean: ')
print(np.logical_not(x, out=x))

y = np.random.uniform(-1,1,50)
print ('original: ')
print (y)
print ('Change the sign of float inplace: ')
print(np.negative(y, out=y))

original: 
[0 0 1 0 0 0 1 0 0 1 0 1 1 1 1 0 1 0 0 0 1 0 0 1 0 1 1 1 0 0 0 1 1 1 1 0 0
 1 0 0 0 1 0 0 0 1 1 1 1 1]
Negating a boolean: 
[1 1 0 1 1 1 0 1 1 0 1 0 0 0 0 1 0 1 1 1 0 1 1 0 1 0 0 0 1 1 1 0 0 0 0 1 1
 0 1 1 1 0 1 1 1 0 0 0 0 0]
original: 
[-0.27129002 -0.04724323 -0.81409507  0.12470681 -0.17911678 -0.28524137
 -0.31027879 -0.56638909 -0.67419199  0.29950719 -0.02503097  0.11217538
  0.46884503 -0.73384328  0.35656561 -0.68947272  0.81256935 -0.68851559
 -0.83478005 -0.95618636 -0.7933714   0.82275998 -0.31255919  0.31505287
 -0.46462518  0.31697883 -0.57370381 -0.96286082 -0.90202768 -0.33703018
  0.46993671  0.60510627 -0.98512289  0.7975097  -0.42284569  0.84311505
  0.80274987  0.8334766  -0.92644389 -0.82186817 -0.89100907  0.12107755
  0.93909048 -0.31064894  0.64289301  0.82680439  0.6135592  -0.77804438
  0.18118436 -0.89889059]
Change the sign of float inplace: 
[ 0.27129002  0.04724323  0.81409507 -0.12470681  0.17911678  0.28524137
  0.31027879  0.56638909  0.67419

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[7.6034122  0.923344   6.54276131 1.75849287 3.45115491 3.37408232
 4.28488484 4.94962988 9.90879301 1.02377903]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,(10,2))
print(np.array([distance(P0,P1,p_i)for p_i in p]))

[[ 7.04320264 13.57589679  1.29374426  1.79398208  7.75607318 16.04550077
  15.24874877  7.43667492  9.07221827  9.84292193]
 [ 6.05459661 13.1462879  11.47899616  1.52758557 10.77123253 12.70666839
   4.31275228  2.55316627  0.09591548  0.07380889]
 [10.19359076  3.46781505  2.37378191 15.81212726  7.22388281  1.56059425
   4.84248583  9.98779805  5.25646111  3.23246814]
 [ 5.36453344  1.78259023  7.67414169 12.88557093  0.33471417  1.35097648
   1.21354535  8.47648983  8.48437752  7.5234485 ]
 [ 1.3438781   7.87322037  1.19377414  3.74395323  2.32784461 10.50968754
  13.07586352  2.15162227  5.35800181  6.64372273]
 [ 9.68131526 16.06184156  0.47130691  5.00595863  9.18176135 19.26133887
  19.1551784  10.97272071 13.13301471 13.89551103]
 [ 9.4150001   2.49535487  1.63558847 15.87162036  5.11472679  1.62647181
   1.48970408 10.6368653   7.6952298   6.03121505]
 [ 9.1913936   2.76485896  7.62496972 13.57327423  8.38943698  0.68733356
  10.88229214  6.93299845  0.03612188  2.34628435]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[3 8 8 3 5 2 2 3 7 4]
 [7 6 4 1 9 2 9 9 0 3]
 [3 5 5 5 1 2 1 1 4 4]
 [5 4 5 2 1 1 8 6 4 3]
 [3 1 3 1 0 7 7 8 7 0]
 [0 8 6 4 9 8 5 9 2 8]
 [8 3 7 6 2 2 8 8 9 3]
 [0 2 9 1 4 7 3 1 2 8]
 [4 2 4 1 7 6 6 8 5 2]
 [7 8 3 5 0 6 9 5 6 8]]
[[0 0 0 0 0]
 [0 3 8 8 3]
 [0 7 6 4 1]
 [0 3 5 5 5]
 [0 5 4 5 2]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = np.lib.stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
arr = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(arr) 
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
n = np.random.randint(0,10,50)
print(np.bincount(n).argmax())

6


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
arr = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (arr.shape[0]-3)
j = 1 + (arr.shape[1]-3)
C = np.lib.stride_tricks.as_strided(arr, shape=(i, j, n, n), strides=arr.strides + arr.strides)
print(C)

[[[[3 3 3]
   [1 3 0]
   [0 0 3]]

  [[3 3 4]
   [3 0 3]
   [0 3 4]]

  [[3 4 3]
   [0 3 4]
   [3 4 4]]

  [[4 3 2]
   [3 4 2]
   [4 4 0]]

  [[3 2 1]
   [4 2 3]
   [4 0 3]]

  [[2 1 4]
   [2 3 2]
   [0 3 3]]

  [[1 4 2]
   [3 2 0]
   [3 3 2]]

  [[4 2 0]
   [2 0 3]
   [3 2 0]]]


 [[[1 3 0]
   [0 0 3]
   [0 0 3]]

  [[3 0 3]
   [0 3 4]
   [0 3 4]]

  [[0 3 4]
   [3 4 4]
   [3 4 0]]

  [[3 4 2]
   [4 4 0]
   [4 0 4]]

  [[4 2 3]
   [4 0 3]
   [0 4 0]]

  [[2 3 2]
   [0 3 3]
   [4 0 0]]

  [[3 2 0]
   [3 3 2]
   [0 0 4]]

  [[2 0 3]
   [3 2 0]
   [0 4 1]]]


 [[[0 0 3]
   [0 0 3]
   [2 2 0]]

  [[0 3 4]
   [0 3 4]
   [2 0 0]]

  [[3 4 4]
   [3 4 0]
   [0 0 2]]

  [[4 4 0]
   [4 0 4]
   [0 2 3]]

  [[4 0 3]
   [0 4 0]
   [2 3 4]]

  [[0 3 3]
   [4 0 0]
   [3 4 2]]

  [[3 3 2]
   [0 0 4]
   [4 2 1]]

  [[3 2 0]
   [0 4 1]
   [2 1 3]]]


 [[[0 0 3]
   [2 2 0]
   [4 4 1]]

  [[0 3 4]
   [2 0 0]
   [4 1 4]]

  [[3 4 0]
   [0 0 2]
   [1 4 3]]

  [[4 0 4]
   [0 2 3]
   [4 3 4]]

  [[0 4 0]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p,n = 10,20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z,np.arange(0,Z.shape[0],k),axis = 0),np.arange(0,Z.shape[1],k),axis = 1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
a = np.arange(1000)
np.random.shuffle(a)
n = 5
print(a[np.argsort(a)[-n:]])

[995 996 997 998 999]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))
print(np.power(x,3))
print(x*x*x)
print(np.einsum('i,i,i->i',x,x,x))

[9.31502478e-02 3.99023910e-03 7.58605399e-02 ... 1.03733435e-01
 9.09433351e-05 3.65821386e-02]
[9.31502478e-02 3.99023910e-03 7.58605399e-02 ... 1.03733435e-01
 9.09433351e-05 3.65821386e-02]
[9.31502478e-02 3.99023910e-03 7.58605399e-02 ... 1.03733435e-01
 9.09433351e-05 3.65821386e-02]


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[...,np.newaxis,np.newaxis]==B)
print(np.where(C.any((3,1)).all(1))[0])

[3]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)

[[0 3 2]
 [3 0 2]
 [2 3 3]
 [1 0 3]
 [3 2 3]
 [3 1 0]
 [4 4 3]
 [1 4 4]
 [3 1 4]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 1 0]
 [0 1 1]
 [1 0 0]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

print(np.einsum('i->', A))      # np.sum(A)
print(np.einsum('i,i->i', A, B)) # A * B
print(np.einsum('i,i', A, B))    # np.inner(A, B)
print(np.einsum('i,j->ij', A, B))    # np.outer(A, B)

5.955981265327718
[0.27772693 0.31610836 0.03114182 0.47740284 0.14894281 0.5410884
 0.3693631  0.17475435 0.37579579 0.04025145]
2.752575841979409
[[0.27772693 0.63466124 0.02590977 0.74246096 0.65178036 0.61312355
  0.68197608 0.16894684 0.59203996 0.04494844]
 [0.1383286  0.31610836 0.01290499 0.36980061 0.32463495 0.30538099
  0.33967466 0.08414806 0.2948798  0.02238765]
 [0.33380924 0.76282047 0.03114182 0.89238854 0.78339651 0.7369336
  0.81968975 0.20306283 0.71159253 0.05402502]
 [0.17857858 0.40808755 0.01666    0.47740284 0.41909515 0.3942388
  0.43851102 0.10863292 0.38068204 0.02890187]
 [0.06346529 0.1450308  0.00592082 0.16966486 0.14894281 0.14010907
  0.15584304 0.0386072  0.13529112 0.01027148]
 [0.24509713 0.56009565 0.02286566 0.65523012 0.57520347 0.5410884
  0.60185153 0.14909748 0.52248189 0.0396675 ]
 [0.15041888 0.34373705 0.01403292 0.40212215 0.35300889 0.33207208
  0.3693631  0.09150281 0.32065306 0.02434439]
 [0.28727373 0.65647758 0.02680041 0.76798289 0.67

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)
print(r[1:])                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)  # integrate path
print(x_int)
y_int = np.interp(r_int, r, y)
print(y_int)

[1.00000000e-01 2.00994225e-01 3.03948099e-01 4.09773428e-01
 5.19310334e-01 6.33316917e-01 7.52465988e-01 8.77347271e-01
 1.00847317e+00 1.14628646e+00 1.29116861e+00 1.44344797e+00
 1.60340735e+00 1.77129076e+00 1.94730924e+00 2.13164591e+00
 2.32446017e+00 2.52589132e+00 2.73606151e+00 2.95507828e+00
 3.18303664e+00 3.42002084e+00 3.66610588e+00 3.92135873e+00
 4.18583938e+00 4.45960178e+00 4.74269456e+00 5.03516168e+00
 5.33704304e+00 5.64837490e+00 5.96919031e+00 6.29951948e+00
 6.63939009e+00 6.98882753e+00 7.34785520e+00 7.71649464e+00
 8.09476576e+00 8.48268698e+00 8.88027538e+00 9.28754684e+00
 9.70451612e+00 1.01311970e+01 1.05676022e+01 1.10137439e+01
 1.14696332e+01 1.19352807e+01 1.24106962e+01 1.28958890e+01
 1.33908678e+01 1.38956409e+01 1.44102161e+01 1.49346005e+01
 1.54688013e+01 1.60128248e+01 1.65666773e+01 1.71303646e+01
 1.77038924e+01 1.82872658e+01 1.88804900e+01 1.94835697e+01
 2.00965094e+01 2.07193135e+01 2.13519861e+01 2.19945311e+01
 2.26469523e+01 2.330925

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.21203252  0.16378408]
